language: node_js
node_js:
- stable
script: bash ./deploy.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "david.davidr@gmail.com"
  - secure: "kgkZsxb7oa/eB6STu1hfGNZk8DZjKG2OzVedv5nRkDQCXuAtcrnl8Y5fl8T69FY1efMJXSxjR9/XGAraiB8bh+P0TkViBdv0ZsbuORSg8YShkYQDIJgfxPUZYd8cvx1WMlldaTi3vldny75iIOFX2/KkPbv1S2TULaTYzK/jn6/gOe20wvnQ41MQOJwAEp5MKGoxwh5bm/MDdEZZtGeoSoFBDHC1CST0InSus2x8bT0SDM9At2elLYwwL1D3ca4M6kEYOqiw1R41SFDZShI+8o9my66t70MnigcOFbX3MFpGExMKlKP7FEv0IubNob4Z9E0Ha+rdJLBTFngyP/y/88KjumFIU5BULZgn8byRgjq5trUBYeBh1eU4r9aEqWBc21oKzjKjXxUU2OsgnSJsWxINW7lHL5+wQUcabfvCfFgzulamqr1NdPYqm5X3TYy1qIVpxJY7vvQO6+fMMZvHvtIBexGiCiOrnTrTvZlnnQ9Qvpa1Fdtw4bSX/k17hw0vSaCKKM8IH5zTbq7uoF2kb7MqEGMREHsgbEzh2PDHMGLfXEjFoyth1rMxclstwYIuOEDrfMJfOSZ2/CZIMPx+We+5AefFT2d5/RcPDCYkiC3hLMSuLYOZKf8Xw4Sv4I0jdqQsAhuyed4bczTZm0cjrAMo7zeKzSTyihYH9X0EPiU="
